services:
  app:
    build: ./website
    image: ai_website
    ports:
      - 3000:3000
    environment:
      # NODE_ENV: development
      # NODE_ENV: production
      DATABASE_URL: ${COMPOSE_DATABASE_URL}
    develop:
      watch:
        - action: sync
          path: ./website
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  db:
    image: postgres:16.7-alpine
    environment:
      POSTGRES_USER: forex
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: tradebotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  python_server:
    build: ./python
    ports:
      - "6000:6000"

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --forward-to http://app:3000/api/webhook --api-key ${STRIPE_RK}"

volumes:
  postgres-data:

    # networks:
    #   goon:
    #     driver: bridge
    # extra_hosts:
    #   "localhost:host-gateway"
