services:
  app:
    build:
      context: .
      # target: final
    image: ai_website
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:1234567890@db:5432/tradebotdb"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size
    # networks:
    #   - goon
    # extra_hosts:
    #   - "localhost:host-gateway"

  db:
    image: postgres:16.7-alpine
    environment: 
      POSTGRES_USER: forex
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: tradebotdb
    ports:
      - "5200:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "3"   # number of files or file count
        max-size: "10m" # file size
    # networks:
    #   - goon
    # extra_hosts:
    #   - "localhost:host-gateway"

volumes:
  postgres-data:

# networks:
#   goon:
#     driver: bridge
# extra_hosts:
#   "localhost:host-gateway"
   